### ISSUE TITLE
Anforderung an Logikkonstruktor

### ISSUE THREAD

**Issue by alxhab** [informatikprojekt-q11-2/repository_name#2]
Wenn der Konstruktor von _GameLogic_ aufgerufen wird, muss die Startposition in der Logik festgelegt werden. Danach wird _GameOverlay.update()_ aufgerufen.

**Comment by Cyention** [comment]
@alxhab , das ist echt eine Enttäuschung, dass du das nicht selbstständig gemacht hast...
